name: Run long e2e tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}

env:
  GINKGO_LABEL_FILTER: ${{ github.event.pull_request.labels && (contains(join(github.event.pull_request.labels.*.name, ','), 'test/full') && 'full' || '') || 'full' }}

jobs:
  e2e_import_gitops:
    uses: ./.github/workflows/run-e2e-suite.yaml
    with:
      test_suite: test/e2e/suites/import-gitops
      test_name: Import via GitOps
      artifact_name: import_gitops
      MANAGEMENT_CLUSTER_ENVIRONMENT: eks
    secrets: inherit
  e2e_v2prov:
    uses: ./.github/workflows/run-e2e-suite.yaml
    with:
      test_suite: test/e2e/suites/v2prov
      test_name: v2 provisioning
      artifact_name: v2prov
      MANAGEMENT_CLUSTER_ENVIRONMENT: eks
    secrets: inherit
  e2e_cleanup:
    if: always()
    needs: [e2e_import_gitops, e2e_v2prov]
    uses: ./.github/workflows/e2e-cleanup.yaml
    secrets: inherit
